CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE IF NOT EXISTS workflow_runs (
  id UUID PRIMARY KEY,
  workflow_type VARCHAR(80) NOT NULL,
  state VARCHAR(80) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS candidate_facts (
  id UUID PRIMARY KEY,
  profile_id UUID NOT NULL,
  category VARCHAR(80) NOT NULL,
  fact_text TEXT NOT NULL,
  verified BOOLEAN NOT NULL DEFAULT FALSE,
  source VARCHAR(255) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

