package com.applyflow.workflow;

public enum WorkflowState {
  CREATED, SEARCHING, ANALYZING, MATCHED, GENERATING, VALIDATING,
  WAITING_FOR_APPROVAL, APPROVED, SUBMITTING, SUBMITTED, TRACKING, RETRYING, FAILED
}

